// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of ChangeUserStatus
  static let ChangeUserStatusPayload = Object(
    typename: "ChangeUserStatusPayload",
    implementedInterfaces: []
  )
}